//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Instituiton
    {
        public System.Guid Id { get; set; }
        public string SchoolName { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string County { get; set; }
        public string Town { get; set; }
        public string PostalAddress { get; set; }
        public string PostalCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string SchoolType { get; set; }
        public Nullable<System.Guid> Createdby_Id { get; set; }
    }
}
