//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_IssueBooksss
    {
        public System.Guid Id { get; set; }
        public System.Guid BorrowerId { get; set; }
        public System.Guid BookId { get; set; }
        public string BookNo { get; set; }
        public string IssuedCopies { get; set; }
        public System.DateTime IssuedDate { get; set; }
        public byte Status { get; set; }
    }
}
