//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_RegisterBooks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_RegisterBooks()
        {
            this.t_LostBooks = new HashSet<t_LostBooks>();
            this.t_ReturnedBooks = new HashSet<t_ReturnedBooks>();
            this.t_IssueBooks = new HashSet<t_IssueBooks>();
        }
    
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string BookNo { get; set; }
        public Nullable<System.Guid> LanguageId { get; set; }
        public string ISBN_No { get; set; }
        public string Edition { get; set; }
        public string Copies { get; set; }
        public Nullable<System.Guid> PublisherId { get; set; }
        public string PublishedYear { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
        public string BarCode { get; set; }
        public string Pages { get; set; }
        public Nullable<System.Guid> AuthorId { get; set; }
        public Nullable<System.Guid> LocationId { get; set; }
        public Nullable<System.Guid> VendorId { get; set; }
    
        public virtual t_Authors t_Authors { get; set; }
        public virtual t_Languages t_Languages { get; set; }
        public virtual t_Location t_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_LostBooks> t_LostBooks { get; set; }
        public virtual t_Publishers t_Publishers { get; set; }
        public virtual t_Vendors t_Vendors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_ReturnedBooks> t_ReturnedBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_IssueBooks> t_IssueBooks { get; set; }
    }
}
